# Read data

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/00_ML/ML_Algos/000-STAGE/DATA_OK.csv", sep =";")

In [4]:
df

N_LST  isTrunc
0      abadgarcia        0
1      abbondante        0
2        abdelgha        1
3         abdelsa        1
4         abdulqa        1
...           ...      ...
72053    thurston        0
72054    draughty        0
72055   henderson        0
72056    espinoza        0
72057   wallowing        0

[72058 rows x 2 columns]

# Data preprocesing

In [5]:
#separate names by space
def separate_string(name):

    name =[" ".join(letter.lower()) for letter in name if letter!=" "]
    return(' '.join(name))


In [6]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [7]:
words = df['N_LST']
words

0        abadgarcia
1        abbondante
2          abdelgha
3           abdelsa
4           abdulqa
            ...    
72053      thurston
72054      draughty
72055     henderson
72056      espinoza
72057     wallowing
Name: N_LST, Length: 72058, dtype: object

In [8]:
words_ngrams = [separate_string(word) for word in words]
print((words_ngrams))

['a b a d g a r c i a', 'a b b o n d a n t e', 'a b d e l g h a', 'a b d e l s a', 'a b d u l q a', 'a b d u r a h i m', 'a b e n d r o t h', 'a b e r c r o m b', 'a b e r c r o m b i e', 'a b e r n a', 'a b e r n e t h y', 'a b i l d s t r', 'a b r a h a', 'a b r a m o w i t z', 'a c c e t t u r i', 'a c h t e r b e r g', 'a c k e r m a n n', 'a c t k i n s o n', 'a d a m e b e r m', 'a d a m s j e n s e n', 'a d a n a n d u s', 'a d d i n g t o n', 'a d v i n c u l a', 'a e n c h b a c h e r', 'a f f l e r b a c h', 'a f i n o w i c z', 'a g h a r a u m u n n a', 'a g u a d o i g l e s', 'a g u e r r i b', 'a g u i l l a r d', 'a h k u w a l i a', 'a h l f i n g e r', 'a h l h a u s', 'a h l s c', 'a h l s c h l a g e r', 'a h l u w a l i a', 'a h r e n', 'a h r e n d s e n', 'a i c h l m a y r', 'a i n s w o r t h', 'a i r i n g t o n', 'a i r r i n g t o n', 'a i t c h i s o n', 'a k i n s b l', 'a l a n i s r e y n a', 'a l a n i s s', 'a l a q u', 'a l b a n e s e j r', 'a l b a 

In [9]:

def compute_max(w_list):
  max_mots = 0
  phrase_max_mots = ""
  # Parcourir chaque phrase dans la liste
  for phrase in w_list:
      # Diviser la phrase en mots en utilisant l'espace comme séparateur
      words = phrase.split()

      # Compter le nombre de mots dans cette phrase
      nb_mots = len(words)

      # Vérifier si cette phrase a plus de mots que la précédente maximum
      if nb_mots > max_mots:
          max_mots = nb_mots
          phrase_max_mots = phrase
  return max_mots
max_len=compute_max(words_ngrams)
max_len

17

In [10]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
voc_size= 26
onehot_repr = [one_hot(words, voc_size) for words in words_ngrams]
onehot_repr

[[13, 18, 13, 20, 21, 13, 11, 23, 14, 13],
 [13, 18, 18, 24, 16, 20, 13, 16, 22, 16],
 [13, 18, 20, 16, 15, 21, 12, 13],
 [13, 18, 20, 16, 15, 17, 13],
 [13, 18, 20, 13, 15, 1, 13],
 [13, 18, 20, 13, 11, 13, 12, 14, 14],
 [13, 18, 16, 16, 20, 11, 24, 22, 12],
 [13, 18, 16, 11, 23, 11, 24, 14, 18],
 [13, 18, 16, 11, 23, 11, 24, 14, 18, 14, 16],
 [13, 18, 16, 11, 16, 13],
 [13, 18, 16, 11, 16, 16, 22, 12, 13],
 [13, 18, 14, 15, 20, 17, 22, 11],
 [13, 18, 11, 13, 12, 13],
 [13, 18, 11, 13, 14, 24, 20, 14, 22, 17],
 [13, 23, 23, 16, 22, 22, 13, 11, 14],
 [13, 23, 12, 22, 16, 11, 18, 16, 11, 21],
 [13, 23, 2, 16, 11, 14, 13, 16, 16],
 [13, 23, 22, 2, 14, 16, 17, 24, 16],
 [13, 20, 13, 14, 16, 18, 16, 11, 14],
 [13, 20, 13, 14, 17, 20, 16, 16, 17, 16, 16],
 [13, 20, 13, 16, 13, 16, 20, 13, 17],
 [13, 20, 20, 14, 16, 21, 22, 24, 16],
 [13, 20, 6, 14, 16, 23, 13, 15, 13],
 [13, 16, 16, 23, 12, 18, 13, 23, 12, 16, 11],
 [13, 24, 24, 15, 16, 11, 18, 13, 23, 12],
 [13, 24, 14, 16, 24, 20, 14, 23,

In [12]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences

In [13]:
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = max_len+3) #all the sentences passed to embedding layer most be the same len
embedded_docs

array([[ 0,  0,  0, ..., 23, 14, 13],
       [ 0,  0,  0, ..., 16, 22, 16],
       [ 0,  0,  0, ..., 21, 12, 13],
       ...,
       [ 0,  0,  0, ..., 17, 24, 16],
       [ 0,  0,  0, ..., 24, 17, 13],
       [ 0,  0,  0, ..., 14, 16, 21]], dtype=int32)

In [14]:
embedded_docs.shape

(72058, 20)

In [15]:
from keras.models import Sequential
#Embedding layer
dim=50
model0 = Sequential()
model0.add(Embedding(voc_size,dim,input_length=max_len+3))

model0.compile('adam', 'mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
#model.summary()

In [17]:
X=model0.predict(embedded_docs)

2252/2252 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step


In [18]:
X.shape

(72058, 20, 50)

In [19]:
# import tensorflow as tf
# X = tf.reshape(X, (X.shape[0], X.shape[2], X.shape[3]))

In [20]:
y=df["isTrunc"]

In [21]:
y.shape

(72058,)

# Model Training

In [22]:

from tensorflow.keras.preprocessing.text import one_hot
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Dropout

In [23]:
from sklearn.model_selection import train_test_split,GridSearchCV
X_train, X_test, y_train , y_test = train_test_split(X,y, test_size=0.2, random_state=12)

In [24]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(57646, 20, 50) (57646,) (14412, 20, 50) (14412,)


In [25]:
#X_train = X_train.reshape(-1,1)
X_train[10].shape

(20, 50)

In [26]:
model = Sequential()
model.add(LSTM(50 , input_shape = (20,50)))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer = 'adam')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 50)                  │          20,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 50)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 20,251 (79.11 KB)

 Trainable params: 20,251 (79.11 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
X_train.shape

(57646, 20, 50)

In [29]:
model.fit(X_train, y_train, validation_data= (X_test, y_test), epochs = 20, batch_size = 32, verbose = 1 )

Epoch 1/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 28s 14ms/step - accuracy: 0.9028 - loss: 0.2668 - val_accuracy: 0.9561 - val_loss: 0.1608
Epoch 2/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9482 - loss: 0.1786 - val_accuracy: 0.9561 - val_loss: 0.1566
Epoch 3/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 22s 12ms/step - accuracy: 0.9507 - loss: 0.1678 - val_accuracy: 0.9561 - val_loss: 0.1517
Epoch 4/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 40s 12ms/step - accuracy: 0.9508 - loss: 0.1664 - val_accuracy: 0.9561 - val_loss: 0.1486
Epoch 5/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 40s 11ms/step - accuracy: 0.9553 - loss: 0.1556 - val_accuracy: 0.9561 - val_loss: 0.1481
Epoch 6/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 22s 12ms/step - accuracy: 0.9551 - loss: 0.1518 - val_accuracy: 0.9559 - val_loss: 0.1494
Epoch 7/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 40s 11ms/step - accuracy: 0.9539 - loss: 0.1535 - val_accuracy: 0.9563 - val_loss: 0.1445
Epoch 8/20
1802/1802 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9556 -

In [30]:
print(2)

2


In [32]:
y[1214], X[1214]

(1,
 array([[-4.0300988e-02,  2.9983427e-02,  3.2307394e-03,  4.2100858e-02,
         -4.1045941e-02,  3.0912388e-02,  4.6739649e-02, -4.6005573e-02,
          2.9064715e-05,  5.3755417e-03, -4.3711092e-02,  2.0464014e-02,
          4.9966086e-02, -2.4097741e-02, -2.1953344e-02,  1.8253874e-02,
          2.3058955e-02,  6.5235384e-03,  1.5928876e-02, -4.1355871e-02,
         -4.4258442e-02, -1.0858320e-02,  1.2205131e-03, -1.0502100e-02,
         -3.3979394e-02, -2.3845350e-02,  4.5383003e-02, -4.6555232e-02,
          1.6270828e-02, -4.7350418e-02, -2.7989412e-02, -1.9751048e-02,
          4.2267572e-02, -2.4771143e-02, -4.6915211e-02,  2.3566697e-02,
          1.6666222e-02, -2.5904883e-02,  3.4430776e-02, -2.6910579e-02,
         -1.4180504e-02,  4.3954138e-02,  5.7788007e-03, -4.6957504e-02,
          3.8257036e-02,  1.8141102e-02,  3.9900076e-02, -3.5212956e-02,
         -4.1228663e-02, -2.7063712e-03],
        [-4.0300988e-02,  2.9983427e-02,  3.2307394e-03,  4.2100858e-02,
     

In [33]:
df['N_LST'][1214]

'camarril'

In [34]:
X_train[0]

array([[-4.0300988e-02,  2.9983427e-02,  3.2307394e-03,  4.2100858e-02,
        -4.1045941e-02,  3.0912388e-02,  4.6739649e-02, -4.6005573e-02,
         2.9064715e-05,  5.3755417e-03, -4.3711092e-02,  2.0464014e-02,
         4.9966086e-02, -2.4097741e-02, -2.1953344e-02,  1.8253874e-02,
         2.3058955e-02,  6.5235384e-03,  1.5928876e-02, -4.1355871e-02,
        -4.4258442e-02, -1.0858320e-02,  1.2205131e-03, -1.0502100e-02,
        -3.3979394e-02, -2.3845350e-02,  4.5383003e-02, -4.6555232e-02,
         1.6270828e-02, -4.7350418e-02, -2.7989412e-02, -1.9751048e-02,
         4.2267572e-02, -2.4771143e-02, -4.6915211e-02,  2.3566697e-02,
         1.6666222e-02, -2.5904883e-02,  3.4430776e-02, -2.6910579e-02,
        -1.4180504e-02,  4.3954138e-02,  5.7788007e-03, -4.6957504e-02,
         3.8257036e-02,  1.8141102e-02,  3.9900076e-02, -3.5212956e-02,
        -4.1228663e-02, -2.7063712e-03],
       [-4.0300988e-02,  2.9983427e-02,  3.2307394e-03,  4.2100858e-02,
        -4.1045941e-02,